#!/bin/sh -e

# To minimize chance of conflict with existing groups, we use "vrui-grp" for the
# system group:
VRUI_GROUP="vrui-grp"
KINECT_ETC="/etc/Vrui-8.0/Kinect-3.10/"

case $1 in
    configure)
        if ! getent group $VRUI_GROUP > /dev/null; then
            addgroup --system $VRUI_GROUP
        fi
        chgrp -R $VRUI_GROUP $KINECT_ETC
        chmod -R g+wX $KINECT_ETC
        ;;
esac

#DEBHELPER#
